apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "penpot.baseConfigName" $ }}-common
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.global.commonLabels "context" $ ) | nindent 4 }}
  {{- if .Values.global.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.global.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
data:
{{- range $cmName, $data := .Values.commonEnv }}
  {{ $cmName }}: {{ (tpl $data $) | quote }}
{{- end }}