apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "taiga.baseConfigName" $ }}-backend-pvc
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.global.commonLabels "context" $ ) | nindent 4 }}
  {{- if .Values.global.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.global.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  accessModes:
  {{- if not (empty .Values.backendPersistence.accessModes) }}
  {{- range .Values.backendPersistence.accessModes }}
    - {{ . | quote }}
  {{- end }}
  {{- else }}
    - {{ .Values.backendPersistence.accessMode | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.backendPersistence.size | quote }}
  {{- include "common.storage.class" (dict "persistence" .Values.backendPersistence "global" .Values.global) | nindent 2 }}
  {{- if .Values.backendPersistence.selector }}
  selector: {{- include "common.tplvalues.render" (dict "value" .Values.backendPersistence.selector "context" $) | nindent 4 }}
  {{- end -}}
  {{- if .Values.backendPersistence.dataSource }}
  dataSource: {{- include "common.tplvalues.render" (dict "value" .Values.backendPersistence.dataSource "context" $) | nindent 4 }}
  {{- end }}