apiVersion: v2
name: penpot
description: A Helm chart for Kubernetes

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 1.0.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "2.0.1-rc.1"

dependencies:
  - name: common
    version: 0.1.0
    repository: file://../common
    alias: backend
  - name: common
    version: 0.1.0
    repository: file://../common
    alias: exporter
  - name: common
    version: 0.1.0
    repository: file://../common
    alias: frontend
  - name: redis
    version: 19.4.0
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
  - name: postgresql
    version: 15.4.0
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: minio
    version: 14.6.0
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled


annotations:
  licenses: Apache-2.0
  images: |
    - name: apache-exporter
      image: docker.io/bitnami/apache-exporter:1.0.7-debian-12-r8
    - name: os-shell
      image: docker.io/bitnami/os-shell:12-debian-12-r21
    - name: penpot-frontend
      image: docker.io/penpotapp/frontend:2.0.1
    - name: penpot-backend
      image: docker.io/penpotapp/backend:2.0.1
    - name: penpot-exporter
      image: docker.io/penpotapp/exporter:2.0.1