apiVersion: v2
name: taiga
description: A Helm chart for Kubernetes

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 1.0.3

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "1.16.0"

dependencies:
  - name: common
    version: 0.1.1
    repository: file://../common
    alias: back
    condition: back.enabled
  - name: common
    version: 0.1.1
    repository: file://../common
    alias: async
    condition: async.enabled
  - name: common
    version: 0.1.1
    repository: file://../common
    alias: front
    condition: front.enabled
  - name: common
    version: 0.1.1
    repository: file://../common
    alias: events
    condition: events.enabled
  - name: common
    version: 0.1.1
    repository: file://../common
    alias: protected
    condition: protected.enabled
  - name: common
    version: 0.1.1
    repository: file://../common
    alias: gateway
    condition: gateway.enabled

annotations:
  licenses: Apache-2.0
  images: |
    - name: apache-exporter
      image: docker.io/bitnami/apache-exporter:1.0.7-debian-12-r8
    - name: os-shell
      image: docker.io/bitnami/os-shell:12-debian-12-r21
    - name: taigo-backend
      image: docker.io/taigaio/taiga-back:6.7.3
    - name: taigo-async
      image: docker.io/taigaio/taiga-back:6.7.3
    - name: taigo-front
      image: docker.io/taigaio/taiga-front:6.7.7
    - name: penpot-events
      image: docker.io/taigaio/taiga-events:6.7.0
    - name: penpot-protected
      image: docker.io/taigaio/taiga-protected:6.7.0
    - name: penpot-gateway
      image: docker.io/nginx:stable-alpine3.19