apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "penpot.fullname" . }}-frontend
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
data:
{{- range $cmName, $data := .Values.frontendEnv }}
  {{ $cmName }}: {{ $data | quote }}
{{- end }}